<a href="https://colab.research.google.com/github/atm028/tf-de-cert-course/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is covering in this notebook:
* introduction to tensors
* getting information from tensors
* manipulating tensors
* Tensors & NumPy
* using tf.function
* using GPUs
* exercises

#Introduction to tensors

In [83]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [84]:
# create tensor with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [85]:
#check number of diensions
scalar.ndim

0

In [86]:
#create vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [87]:
vector.ndim

1

In [88]:
#matrix
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [89]:
matrix.ndim

2

In [90]:
#tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [91]:
tensor.ndim

2

##Creatng tensors with tf.Variable

In [92]:
changable_tensor = tf.Variable([10., 7.], dtype=tf.float32)
unchangable_tensor = tf.constant([10., 7.], dtype=tf.float32)
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([10.,  7.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>)

In [93]:
#changable_tensor[0] = 20.
#changable_tensor

In [94]:
changable_tensor[0].assign(20.)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([20.,  7.], dtype=float32)>

##Creating random tesnors

In [95]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2)) 

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2)) 
random_1, random_1, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [96]:
random_1.ndim

2

### shuffle the order of elements in tensor

In [97]:
#shuffle a tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

In [98]:
not_shuffled.ndim

2

In [99]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

**Exercise:** Read through Tesnorflow documentaion on random seed generation: [https://www.tensorflow.org/api_docs/python/tf/random/set_seed](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) and practice writing 5 random tesnors and shuffle them.

##Create tesnors from NumPy

In [100]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [101]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [102]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) - capital for matrix
# y = tf.constant(vector) - non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [103]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

##Getting information from tensors
* Shape
* Rank
* Axis of dimension
* Size

In [104]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [105]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [106]:
#Get various attributes of tensor
print("Datatype of every element", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Eements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Eements along the last axis:  5
Total number of elements in tensor:  120


## Indexing tensors
Tensors can be indexed just like Python lists

In [107]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [108]:
# get the first element from each dimension from each index exept for the final one
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [109]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[2, 7],
                             [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 7],
       [3, 4]], dtype=int32)>

In [110]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [7]],

       [[3],
        [4]]], dtype=int32)>

In [111]:
tf.expand_dims(rank_2_tensor, axis=-1) #-1 - means expand last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [7]],

       [[3],
        [4]]], dtype=int32)>

In [112]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 7],
        [3, 4]]], dtype=int32)>

## Manipulating tensors

**Basic operations**
`+`, `-`, `*`, `/`

In [113]:
tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [114]:
tensor+10

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]], dtype=int32)>

In [115]:
tensor*10

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]], dtype=int32)>

In [116]:
tensor-10

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]], dtype=int32)>

In [117]:
tensor/2

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])>

In [118]:
#we can use the TF uild-in functions too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]], dtype=int32)>

**Matrix multiplications**

In ML is most common tesnor operations

In [119]:
# matrix multiplication in TF
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [120]:
# matrix multiplication with Python

In [121]:
tensor @ tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [122]:
# exersise
A = tf.constant([[1, 2, 5],
                 [7, 2, 1],
                 [3, 3, 3]])
B = tf.constant([[3, 5],
                 [6, 7],
                 [1, 8]])
tf.linalg.matmul(A, B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [123]:
#Matmul not matched arrays
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                [9, 10],
                [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [124]:
# tf.linalg.matmul(X, Y) - will not work since shape mismatch

In [125]:
# since inner size of shapes should be same then we have to reshape the Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [126]:
tf.linalg.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [127]:
#or X
tf.reshape(X, shape=(2, 3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

It's obvious that result of X @ reshapedY and reshapedX @ Y will be different. It could be found from rules of matrix multiplications in linalg. If 3x2 dot 2x3 then the result will be outter shapes of matrixs, i.e 3x3.
In case of 2x3 dot 3x2 result will be 2x2

In [128]:
#but we can use alse transpose instead of reshape
tf.linalg.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Why results are different. It because the transpose and reshape are works differently.

In [129]:
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

**The dot product**
Matrix multiplication is also referred to as the dot product
You can perform matrix multiplication using:
* `tf.linalg.matmul`
* `tf.tensordot`

In [130]:
#perform the dot product on X and Y using transpose
tf.tensordot(tf.transpose(X), Y, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Exersise** read about `tf.tensordot` and try using different axises

## Changing the datatype of tensors

In [131]:
#create with default datatype(float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [132]:
C = tf.constant([1, 2])
C.dtype

tf.int32

In [133]:
# float32 -> float16
tf.cast(B, tf.float16).dtype

tf.float16

## Tensor aggregations
* min
* max
* mean
* sum

In [134]:
# get the absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [135]:
E = tf.constant(np.random.randint(0, 100, 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 3, 46, 81, 54, 94, 40, 64, 81, 80, 28, 53, 98, 78, 20, 19, 51, 17,
       44, 55, 83, 30, 31, 49,  7, 31, 43, 31, 31, 54, 83, 81, 52,  1, 86,
       54, 49, 73, 80, 31, 73, 87, 90, 40, 31, 26, 48, 86, 83, 57,  3])>

In [136]:
#min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [137]:
#max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [138]:
#mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [139]:
#sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2610>

In [140]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=704.5>

In [141]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=704>

In [142]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=26.55>

## Find the positional max and min of a tensor

In [143]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [144]:
# Find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [145]:
#Index on largest value positin
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [146]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [147]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [148]:
# Find the positional min
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [149]:
F[tf.argmin(E)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.81179297>

In [150]:
tf.reduce_min(F) == F[tf.argmin(E)]

<tf.Tensor: shape=(), dtype=bool, numpy=False>

## Squeezing a tensor (removing all single dimensions)

In [151]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [152]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [153]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

## One hot encoding tensors

In [154]:
# create list of indicies
someList = [0, 1, 2, 3]

#One-hot encode this list
tf.one_hot(someList, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [155]:
# specify custom values for one hot encoding
tf.one_hot(someList, depth=4, on_value="A", off_value="B")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'A', b'B', b'B', b'B'],
       [b'B', b'A', b'B', b'B'],
       [b'B', b'B', b'A', b'B'],
       [b'B', b'B', b'B', b'A']], dtype=object)>

## More tensor math operations

In [156]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [157]:
#square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [158]:
#sqrt (requires non-int args)
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [159]:
#log (also requires non-int args)
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

## Exploring TF and NP's compatibility
TF interacts with NP arrays


In [160]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [161]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [162]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [163]:
# The default type of each slightly different
np_J = tf.constant(np.array([3., 7., 10.]))
tf_J = tf.constant([3., 7., 10.])
np_J.dtype, tf_J.dtype

(tf.float64, tf.float32)

## Use GPU and check it is faster than CPU


In [164]:
# check access to GPU - it's possible to enable the GPU and TPU in Runtime - > Change runtime type
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [165]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



The check above doesn't work for TPU, correct way explained in the official doc 
[How to work with TPU](https://colab.research.google.com/notebooks/tpu.ipynb)

In [166]:
#Checking the TPU as recommended by Google
try:
  tpu = tf.distribute.cluster_resolver.TPUClusterResolver() #TPU detection
  print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
except:
  raise BaseException('ERROR: Not connected to a TPU runtime.')

tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)

Running on TPU  ['10.97.37.218:8470']
INFO:tensorflow:Initializing the TPU system: grpc://10.97.37.218:8470


INFO:tensorflow:Initializing the TPU system: grpc://10.97.37.218:8470


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)
